In [1]:
# Задание 1
# Импортируйте библиотеку Numpy и дайте ей псевдоним np.

import numpy as np

# Создайте массив Numpy под названием a размером 5x2, то есть состоящий из 5 строк и 2 столбцов. 
# Первый столбец должен содержать числа 1, 2, 3, 3, 1, а второй - числа 6, 8, 11, 10, 7.


a = np.array([[1, 6],
[2, 8],
[3, 11],
[3,10],
[1,7]])

print(a)
print("Размерность a: {}".format(a.ndim))
print("Форма а: {}".format(a.shape))


[[ 1  6]
 [ 2  8]
 [ 3 11]
 [ 3 10]
 [ 1  7]]
Размерность a: 2
Форма а: (5, 2)


In [2]:
print("Средние значения столбцов: {}".format(a.mean(axis=0)))


Средние значения столбцов: [2.  8.4]


In [3]:
mean_a = np.array(a.mean(axis=0))


In [4]:
print(mean_a)

[2.  8.4]


In [5]:
## Задание 2
## вычислить массив a_centered отняв от значений массива а средние значения признаков в mean_a 

a_centered = a - mean_a

In [6]:
print(a_centered)


[[-1.  -2.4]
 [ 0.  -0.4]
 [ 1.   2.6]
 [ 1.   1.6]
 [-1.  -1.4]]


In [7]:
print("Форма а_centered: {}".format(a_centered.shape))

Форма а_centered: (5, 2)


In [8]:
## Задание 3
## Найти скалярное произведение столбцов массива a_centered
print( a_centered[0,0])
print( a_centered[0,1])

-1.0
-2.4000000000000004


In [9]:
a1 = a_centered[:,0]
a2 = a_centered[:,1]
a_centered_sp = a1@a2
print(a1)
print(a2)
print(a_centered_sp)

[-1.  0.  1.  1. -1.]
[-2.4 -0.4  2.6  1.6 -1.4]
8.0


In [10]:
## Делим a_center_sp на число N-1 где N - число наблюдений ( = 5)
print(a_centered_sp / 4)


2.0


In [11]:
## Задание 4.
## Транспонируем матрицу a и вычисляем ковариацию с помощью функции np.cov()
a_transpon = np.transpose(a)
print(a_transpon)
print(np.cov(a_transpon))


[[ 1  2  3  3  1]
 [ 6  8 11 10  7]]
[[1.  2. ]
 [2.  4.3]]


In [12]:
## Таким образом ковариация равна элементу в строке с индексом 0 и столбце с индексом 1 - [0,1]
print(np.cov(a_transpon)[0,1])


2.0


In [13]:
## Тема "Работа с данными в Pandas"

## Задание 1
## Импортируйте библиотеку Pandas и дайте ей псевдоним pd.

import pandas as pd
import numpy as np

## Создайте датафрейм authors со столбцами author_id и author_name, в которых соответственно содержаться данные:
## [1,2,3] и ['Тургенев', 'Чехов', 'Островский']

dfr = {"author_id":np.array([1,2,3]), "author_name":np.array(['Тургенев', 'Чехов', 'Островский']) }

authors = pd.DataFrame(dfr)

print(authors)

 

   author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский


In [14]:
## Затем создайте датафрейм book cо столбцами author_id, book_title и price,
## в которых соответственно содержатся данные:  
## [1, 1, 1, 2, 2, 3, 3],
## ['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой',
## 'Гроза', 'Таланты и поклонники'],
## [450, 300, 350, 500, 450, 370, 290].

d = {"author_id":np.array([1, 1, 1, 2, 2, 3, 3]), "book_title":np.array(['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой','Гроза', 'Таланты и поклонники']), "price":np.array([450, 300, 350, 500, 450, 370, 290] ) }

book = pd.DataFrame(d)

print(book)


   author_id            book_title  price
0          1           Отцы и дети    450
1          1                 Рудин    300
2          1     Дворянское гнездо    350
3          2      Толстый и тонкий    500
4          2       Дама с собачкой    450
5          3                 Гроза    370
6          3  Таланты и поклонники    290


In [15]:
## Задание 2 .
## Получите датафрейм authors_price, соединив датафреймы authors и books по полю author_id
authors_price = authors.merge(book, on=["author_id"])
print(authors_price)


   author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290


In [16]:
## Задание 3
## Создайте датафрейм top5, в котором содержатся строки из authors_price с пятью самыми дорогими книгами.

## print(authors_price.sort_values('price'))
authors_price_top = authors_price.sort_values('price')

print(authors_price_top)


   author_id author_name            book_title  price
6          3  Островский  Таланты и поклонники    290
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
5          3  Островский                 Гроза    370
0          1    Тургенев           Отцы и дети    450
4          2       Чехов       Дама с собачкой    450
3          2       Чехов      Толстый и тонкий    500


In [17]:
top5 = authors_price_top.head(5)
print(top5)

   author_id author_name            book_title  price
6          3  Островский  Таланты и поклонники    290
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
5          3  Островский                 Гроза    370
0          1    Тургенев           Отцы и дети    450


In [26]:
## Задание 4
## Создайте датафрейм authors_stat на основе информации из authors_price. В датафрейме authors_stat
## должны быть четыре столбца:
## author_name, min_price, max_price и mean_price,
## в которых должны содержаться соответственно имя автора, минимальная, максимальная и средняя цена
## на книги этого автора.

b = authors_price[['author_name', 'price']].groupby('author_name').describe()
print (b)




            price                                                          
            count        mean        std    min    25%    50%    75%    max
author_name                                                                
Островский    2.0  330.000000  56.568542  290.0  310.0  330.0  350.0  370.0
Тургенев      3.0  366.666667  76.376262  300.0  325.0  350.0  400.0  450.0
Чехов         2.0  475.000000  35.355339  450.0  462.5  475.0  487.5  500.0


In [27]:
authors_stat = b['price'][['min', 'max', 'mean']]
print(authors_stat)


               min    max        mean
author_name                          
Островский   290.0  370.0  330.000000
Тургенев     300.0  450.0  366.666667
Чехов        450.0  500.0  475.000000


In [28]:
## Задание 5
## Задание 5**
##Создайте новый столбец в датафрейме authors_price под названием cover,
##в нем будут располагаться данные о том, какая обложка у данной книги - твердая или мягкая.
##В этот столбец поместите данные из следующего списка:
##['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая'].
##Просмотрите документацию по функции pd.pivot_table с помощью вопросительного знака.
##Для каждого автора посчитайте суммарную стоимость книг в твердой и мягкой обложке.
##Используйте для этого функцию pd.pivot_table. При этом столбцы должны называться "твердая" и "мягкая",
##а индексами должны быть фамилии авторов. Пропущенные значения стоимостей заполните нулями,
##при необходимости загрузите библиотеку Numpy.
##Назовите полученный датасет book_info и сохраните его в формат pickle под названием "book_info.pkl".
##Затем загрузите из этого файла датафрейм и назовите его book_info2. Удостоверьтесь,
##что датафреймы book_info и book_info2 идентичны.

authors_price['cover'] = ['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая']

book_info = authors_price[['author_name', 'cover', 'price']].pivot_table(index='author_name', columns='cover', aggfunc=sum).fillna(0)
print(book_info)



             price        
cover       мягкая твердая
author_name               
Островский   660.0     0.0
Тургенев     650.0   450.0
Чехов          0.0   950.0


In [29]:
book_info.to_pickle('book_info.pkl')
